INPUT_STATE_SIZE = 3
OUTPUT_STATE_SIZE = 3
LATENT_DIM = 2

INPUT_DIMENSION = INPUT_STATE_SIZE * 4
OUTPUT_DIMENSION =  OUTPUT_STATE_SIZE * 4

ENCODER_HIDDEN = 12
ENCODER_HIDDEN2= 10
ENCODER_HIDDEN3 = 8
ENCODER_HIDDEN4 = 6
DECODER_HIDDEN = 6
DECODER_HIDDEN2 = 8
DECODER_HIDDEN3= 10
DECODER_HIDDEN4 = 12

BETA_KL_DIV= 0.2

TRAIN_FREQUENCY = 3

EPOCHS = 10

LOSS_FUNC= "MSE_loss_feature_Standardization"

ACT_FUNC = "LeakyReLU(0.1)"

EVAL_SEED = [1, 33, 545, 65 ,6 , 66, 78, 48 , 24 , 98]

VAE_Version = "VAE_Version_9"

