INPUT_STATE_SIZE = 5
OUTPUT_STATE_SIZE = 2
LATENT_DIM = 5
INPUT_DIMENSION = 120
OUTPUT_DIMENSION = 48
ENCODER_HIDDEN = 45
ENCODER_HIDDEN2 = 35
ENCODER_HIDDEN3 = 25
ENCODER_HIDDEN4 = 15
ENCODER_HIDDEN5 = 0
ENCODER_HIDDEN6 = 0
ENCODER_HIDDEN7 = 0
ENCODER_HIDDEN8 = 0
DECODER_HIDDEN = 15
DECODER_HIDDEN2 = 25
DECODER_HIDDEN3 = 35
DECODER_HIDDEN4 = 45
DECODER_HIDDEN5 = 0
DECODER_HIDDEN6 = 0
DECODER_HIDDEN7 = 0
DECODER_HIDDEN8 = 0
BETA_KL_DIV = 0.00078
TRAIN_FREQUENCY = 5
EPOCHS = 2

LOSS_FUNC = "MSE_loss_feature_Standardization"

ACT_FUNC = "LeakyReLU(0.1)"
NORM_FUNC = "LayerNorm"

VAE_Version = "VAE_Version_4.14"

ENCODER_HIDDEN9 = 16
DECODER_HIDDEN9 = 16