INPUT_STATE_SIZE = 4
OUTPUT_STATE_SIZE = 2
LATENT_DIM = 4

INPUT_DIMENSION = INPUT_STATE_SIZE * 24
OUTPUT_DIMENSION =  OUTPUT_STATE_SIZE * 24

ENCODER_HIDDEN = 16
ENCODER_HIDDEN2 = 12
ENCODER_HIDDEN3 = 10
ENCODER_HIDDEN4 = 6
ENCODER_HIDDEN5 = 6
ENCODER_HIDDEN6 = 6
ENCODER_HIDDEN7 = 6
ENCODER_HIDDEN8 = 6

DECODER_HIDDEN = 6
DECODER_HIDDEN2 = 6
DECODER_HIDDEN3 = 8
DECODER_HIDDEN4 = 8
DECODER_HIDDEN5 = 8
DECODER_HIDDEN6 = 8
DECODER_HIDDEN7 = 8


BETA_KL_DIV = 0.001
TRAIN_FREQUENCY = 5
EPOCHS = 3
LOSS_FUNC = "MSE_loss_feature_Standardization"
ENCODER_N_LAYERS = 6
DECODER_N_LAYERS = 6
ACT_FUNC = "LeakyReLU(0.1)"
NORM_FUNC = "LayerNorm"

VAE_Version = "VAE_Version_3.17"

