SUITE_CONFIGS = {
    'config_compact': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 32,
        'ENCODER_HIDDEN3': 16,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 16,
        'DECODER_HIDDEN2': 32,
        'DECODER_HIDDEN3': 48,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.1"
    },

    'config_bottleneck': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 2,
        'ENCODER_HIDDEN': 64,
        'ENCODER_HIDDEN2': 32,
        'ENCODER_HIDDEN3': 16,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 16,
        'DECODER_HIDDEN2': 32,
        'DECODER_HIDDEN3': 64,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.2"
    },

    'config_wide': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 8,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 64,
        'ENCODER_HIDDEN3': 32,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 32,
        'DECODER_HIDDEN2': 64,
        'DECODER_HIDDEN3': 96,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0005,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.3"
    },

    'config_minimal': {
        'INPUT_STATE_SIZE': 1,
        'OUTPUT_STATE_SIZE': 1,
        'LATENT_DIM': 2,
        'ENCODER_HIDDEN': 24,
        'ENCODER_HIDDEN2': 16,
        'ENCODER_HIDDEN3': 8,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 8,
        'DECODER_HIDDEN2': 16,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0003,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.4"
    },

    'config_latent_rich': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 12,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 48,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 24,
        'DECODER_HIDDEN2': 48,
        'DECODER_HIDDEN3': 72,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.5"
    },

    'config_dense': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 6,
        'ENCODER_HIDDEN': 84,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 36,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 36,
        'DECODER_HIDDEN2': 72,
        'DECODER_HIDDEN3': 84,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.6"
    },

    'config_asymmetric': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 48,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 24,
        'DECODER_HIDDEN2': 36,
        'DECODER_HIDDEN3': 48,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0005,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.7"
    },

    'config_micro': {
        'INPUT_STATE_SIZE': 1,
        'OUTPUT_STATE_SIZE': 1,
        'LATENT_DIM': 1,
        'ENCODER_HIDDEN': 12,
        'ENCODER_HIDDEN2': 8,
        'ENCODER_HIDDEN3': 4,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 4,
        'DECODER_HIDDEN2': 8,
        'DECODER_HIDDEN3': 12,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.8"
    },

    'config_complex': {
        'INPUT_STATE_SIZE': 4,
        'OUTPUT_STATE_SIZE': 4,
        'LATENT_DIM': 8,
        'ENCODER_HIDDEN': 120,
        'ENCODER_HIDDEN2': 90,
        'ENCODER_HIDDEN3': 60,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 60,
        'DECODER_HIDDEN2': 90,
        'DECODER_HIDDEN3': 120,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0003,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.9"
    },

    'config_balanced': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 5,
        'ENCODER_HIDDEN': 60,
        'ENCODER_HIDDEN2': 40,
        'ENCODER_HIDDEN3': 20,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 20,
        'DECODER_HIDDEN2': 40,
        'DECODER_HIDDEN3': 60,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.10"
    },

    'config_narrow': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 3,
        'ENCODER_HIDDEN': 36,
        'ENCODER_HIDDEN2': 24,
        'ENCODER_HIDDEN3': 12,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 24,
        'DECODER_HIDDEN3': 36,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.11"
    },

    'config_exp_decay': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 64,
        'ENCODER_HIDDEN2': 32,
        'ENCODER_HIDDEN3': 16,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 16,
        'DECODER_HIDDEN2': 32,
        'DECODER_HIDDEN3': 64,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0005,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.12"
    },

    'config_deeper_latent': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 16,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 64,
        'ENCODER_HIDDEN3': 32,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 32,
        'DECODER_HIDDEN2': 64,
        'DECODER_HIDDEN3': 96,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0003,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.13"
    },

    'config_wider_io': {
        'INPUT_STATE_SIZE': 5,
        'OUTPUT_STATE_SIZE': 5,
        'LATENT_DIM': 8,
        'ENCODER_HIDDEN': 144,
        'ENCODER_HIDDEN2': 96,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 48,
        'DECODER_HIDDEN2': 96,
        'DECODER_HIDDEN3': 144,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.14"
    },

    'config_pyramid': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 6,
        'ENCODER_HIDDEN': 108,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 36,
        'ENCODER_HIDDEN4': 0,
        'ENCODER_HIDDEN5': 0,
        'ENCODER_HIDDEN6': 0,
        'ENCODER_HIDDEN7': 0,
        'ENCODER_HIDDEN8': 0,
        'DECODER_HIDDEN': 36,
        'DECODER_HIDDEN2': 72,
        'DECODER_HIDDEN3': 108,
        'DECODER_HIDDEN4': 0,
        'DECODER_HIDDEN5': 0,
        'DECODER_HIDDEN6': 0,
        'DECODER_HIDDEN7': 0,
        'DECODER_HIDDEN8': 0,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_4.15"
    }
}