SUITE_CONFIGS = {
    'compact_latent_2': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 2,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 32,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 12,
        'ENCODER_HIDDEN5': 10,
        'ENCODER_HIDDEN6': 8,
        'ENCODER_HIDDEN7': 6,
        'ENCODER_HIDDEN8': 4,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 24,
        'DECODER_HIDDEN3': 32,
        'DECODER_HIDDEN4': 48,
        'DECODER_HIDDEN5': 24,
        'DECODER_HIDDEN6': 16,
        'DECODER_HIDDEN7': 8,
        'DECODER_HIDDEN8': 4,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.1"
    },

    'medium_latent_4': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 64,
        'ENCODER_HIDDEN2': 48,
        'ENCODER_HIDDEN3': 32,
        'ENCODER_HIDDEN4': 24,
        'ENCODER_HIDDEN5': 16,
        'ENCODER_HIDDEN6': 12,
        'ENCODER_HIDDEN7': 8,
        'ENCODER_HIDDEN8': 6,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 24,
        'DECODER_HIDDEN3': 32,
        'DECODER_HIDDEN4': 48,
        'DECODER_HIDDEN5': 64,
        'DECODER_HIDDEN6': 32,
        'DECODER_HIDDEN7': 16,
        'DECODER_HIDDEN8': 8,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.2"
    },

    'large_latent_8': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 8,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 64,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 32,
        'ENCODER_HIDDEN5': 24,
        'ENCODER_HIDDEN6': 16,
        'ENCODER_HIDDEN7': 12,
        'ENCODER_HIDDEN8': 10,
        'DECODER_HIDDEN': 16,
        'DECODER_HIDDEN2': 32,
        'DECODER_HIDDEN3': 48,
        'DECODER_HIDDEN4': 64,
        'DECODER_HIDDEN5': 96,
        'DECODER_HIDDEN6': 48,
        'DECODER_HIDDEN7': 24,
        'DECODER_HIDDEN8': 12,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.3"
    },

    'balanced_narrow': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 3,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 48,
        'ENCODER_HIDDEN3': 36,
        'ENCODER_HIDDEN4': 24,
        'ENCODER_HIDDEN5': 18,
        'ENCODER_HIDDEN6': 12,
        'ENCODER_HIDDEN7': 8,
        'ENCODER_HIDDEN8': 6,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 18,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 36,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 36,
        'DECODER_HIDDEN8': 18,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.4"
    },

    'wide_bottleneck': {
        'INPUT_STATE_SIZE': 4,
        'OUTPUT_STATE_SIZE': 4,
        'LATENT_DIM': 2,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 32,
        'ENCODER_HIDDEN5': 24,
        'ENCODER_HIDDEN6': 16,
        'ENCODER_HIDDEN7': 8,
        'ENCODER_HIDDEN8': 4,
        'DECODER_HIDDEN': 8,
        'DECODER_HIDDEN2': 16,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 32,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 96,
        'DECODER_HIDDEN8': 48,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.5"
    },

    'deep_narrow': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 1,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 36,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 18,
        'ENCODER_HIDDEN5': 12,
        'ENCODER_HIDDEN6': 8,
        'ENCODER_HIDDEN7': 4,
        'ENCODER_HIDDEN8': 2,
        'DECODER_HIDDEN': 4,
        'DECODER_HIDDEN2': 8,
        'DECODER_HIDDEN3': 12,
        'DECODER_HIDDEN4': 18,
        'DECODER_HIDDEN5': 24,
        'DECODER_HIDDEN6': 36,
        'DECODER_HIDDEN7': 48,
        'DECODER_HIDDEN8': 24,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.6"
    },

    'asymmetric_wide': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 54,
        'ENCODER_HIDDEN3': 36,
        'ENCODER_HIDDEN4': 24,
        'ENCODER_HIDDEN5': 16,
        'ENCODER_HIDDEN6': 12,
        'ENCODER_HIDDEN7': 8,
        'ENCODER_HIDDEN8': 6,
        'DECODER_HIDDEN': 10,
        'DECODER_HIDDEN2': 16,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 36,
        'DECODER_HIDDEN5': 54,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 90,
        'DECODER_HIDDEN8': 72,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.7"
    },

    'compact_medium': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 3,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 32,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 16,
        'ENCODER_HIDDEN5': 12,
        'ENCODER_HIDDEN6': 8,
        'ENCODER_HIDDEN7': 6,
        'ENCODER_HIDDEN8': 4,
        'DECODER_HIDDEN': 8,
        'DECODER_HIDDEN2': 16,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 32,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 24,
        'DECODER_HIDDEN7': 12,
        'DECODER_HIDDEN8': 6,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.8"
    },

    'hourglass_4': {
        'INPUT_STATE_SIZE': 4,
        'OUTPUT_STATE_SIZE': 4,
        'LATENT_DIM': 4,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 32,
        'ENCODER_HIDDEN5': 16,
        'ENCODER_HIDDEN6': 12,
        'ENCODER_HIDDEN7': 8,
        'ENCODER_HIDDEN8': 6,
        'DECODER_HIDDEN': 8,
        'DECODER_HIDDEN2': 12,
        'DECODER_HIDDEN3': 16,
        'DECODER_HIDDEN4': 32,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 96,
        'DECODER_HIDDEN8': 72,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.9"
    },

    'pyramid_6': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 6,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 60,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 36,
        'ENCODER_HIDDEN5': 24,
        'ENCODER_HIDDEN6': 18,
        'ENCODER_HIDDEN7': 12,
        'ENCODER_HIDDEN8': 8,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 18,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 36,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 60,
        'DECODER_HIDDEN7': 72,
        'DECODER_HIDDEN8': 60,
        'BETA_KL_DIV': 0.0007,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.10"
    },

    'wide_shallow': {
        'INPUT_STATE_SIZE': 4,
        'OUTPUT_STATE_SIZE': 4,
        'LATENT_DIM': 6,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 54,
        'ENCODER_HIDDEN4': 42,
        'ENCODER_HIDDEN5': 32,
        'ENCODER_HIDDEN6': 24,
        'ENCODER_HIDDEN7': 16,
        'ENCODER_HIDDEN8': 12,
        'DECODER_HIDDEN': 16,
        'DECODER_HIDDEN2': 24,
        'DECODER_HIDDEN3': 32,
        'DECODER_HIDDEN4': 42,
        'DECODER_HIDDEN5': 54,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 96,
        'DECODER_HIDDEN8': 80,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.11"
    },

    'bottleneck_steep': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 2,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 36,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 16,
        'ENCODER_HIDDEN5': 8,
        'ENCODER_HIDDEN6': 6,
        'ENCODER_HIDDEN7': 4,
        'ENCODER_HIDDEN8': 3,
        'DECODER_HIDDEN': 4,
        'DECODER_HIDDEN2': 6,
        'DECODER_HIDDEN3': 8,
        'DECODER_HIDDEN4': 16,
        'DECODER_HIDDEN5': 24,
        'DECODER_HIDDEN6': 36,
        'DECODER_HIDDEN7': 48,
        'DECODER_HIDDEN8': 36,
        'BETA_KL_DIV': 0.001,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.12"
    },

    'balanced_gradual': {
        'INPUT_STATE_SIZE': 3,
        'OUTPUT_STATE_SIZE': 3,
        'LATENT_DIM': 5,
        'ENCODER_HIDDEN': 72,
        'ENCODER_HIDDEN2': 60,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 36,
        'ENCODER_HIDDEN5': 24,
        'ENCODER_HIDDEN6': 18,
        'ENCODER_HIDDEN7': 12,
        'ENCODER_HIDDEN8': 8,
        'DECODER_HIDDEN': 12,
        'DECODER_HIDDEN2': 18,
        'DECODER_HIDDEN3': 24,
        'DECODER_HIDDEN4': 36,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 60,
        'DECODER_HIDDEN7': 72,
        'DECODER_HIDDEN8': 60,
        'BETA_KL_DIV': 0.0009,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.13"
    },

    'assymetric_compact': {
        'INPUT_STATE_SIZE': 2,
        'OUTPUT_STATE_SIZE': 2,
        'LATENT_DIM': 3,
        'ENCODER_HIDDEN': 48,
        'ENCODER_HIDDEN2': 36,
        'ENCODER_HIDDEN3': 24,
        'ENCODER_HIDDEN4': 18,
        'ENCODER_HIDDEN5': 12,
        'ENCODER_HIDDEN6': 8,
        'ENCODER_HIDDEN7': 6,
        'ENCODER_HIDDEN8': 4,
        'DECODER_HIDDEN': 6,
        'DECODER_HIDDEN2': 10,
        'DECODER_HIDDEN3': 16,
        'DECODER_HIDDEN4': 24,
        'DECODER_HIDDEN5': 36,
        'DECODER_HIDDEN6': 48,
        'DECODER_HIDDEN7': 36,
        'DECODER_HIDDEN8': 24,
        'BETA_KL_DIV': 0.0008,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.14"
    },

    'extreme_bottleneck': {
        'INPUT_STATE_SIZE': 4,
        'OUTPUT_STATE_SIZE': 4,
        'LATENT_DIM': 1,
        'ENCODER_HIDDEN': 96,
        'ENCODER_HIDDEN2': 72,
        'ENCODER_HIDDEN3': 48,
        'ENCODER_HIDDEN4': 32,
        'ENCODER_HIDDEN5': 16,
        'ENCODER_HIDDEN6': 8,
        'ENCODER_HIDDEN7': 4,
        'ENCODER_HIDDEN8': 2,
        'DECODER_HIDDEN': 4,
        'DECODER_HIDDEN2': 8,
        'DECODER_HIDDEN3': 16,
        'DECODER_HIDDEN4': 32,
        'DECODER_HIDDEN5': 48,
        'DECODER_HIDDEN6': 72,
        'DECODER_HIDDEN7': 96,
        'DECODER_HIDDEN8': 80,
        'BETA_KL_DIV': 0.0007,
        'TRAIN_FREQUENCY': 5,
        'LOSS_FUNC': "MSE_loss_feature_Standardization",
        'EPOCHS': 2,
        'ACT_FUNC': "LeakyReLU(0.1)",
        'NORM_FUNC': "LayerNorm",
        'EVAL_SEED': [1, 33, 545, 65, 6, 66, 78, 48, 24, 98],
        'VAE_Version': "VAE_Version_3.15"
    }
}